name: Translate README

on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      # ISO Langusge Codes: https://cloud.google.com/translate/docs/languages

      - name: Adding README - 한국어
        uses: dephraiim/translate-readme@main
        with:
          LANG: ko

      - name: Adding README - 繁體中文
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-TW

      - name: Adding README - Hindi
        uses: dephraiim/translate-readme@main
        with:
          LANG: hi

      - name: Adding README - Arabic
        uses: dephraiim/translate-readme@main
        with:
          LANG: ar

      - name: Adding README - Français
        uses: dephraiim/translate-readme@main
        with:
          LANG: fr

      - name: Adding README - Русский
        uses: dephraiim/translate-readme@main
        with:
          LANG: ru

      - name: Adding README - 日本語
        uses: dephraiim/translate-readme@main
        with:
          LANG: ja

      - name: Adding README - Italian
        uses: dephraiim/translate-readme@main
        with:
          LANG: it

      - name: Adding README - Deutsch
        uses: dephraiim/translate-readme@main
        with:
          LANG: de

      - name: Adding README - Español
        uses: dephraiim/translate-readme@main
        with:
          LANG: es

      - name: Adding README - svenska
        uses: dephraiim/translate-readme@main
        with:
          LANG: sv